[CMOB-1460]added colors, dimens.. created intro & home fragments, painted rectang…
ninikokra/Quiz pull request #1
Opened 2023-05-17 00:22 UTC by ninikokra

https://spaceneobank.atlassian.net/jira/software/c/projects/CMOB/issues/CMOB-1460

2023-05-19 08:32 UTC, AnaRusadze requested changes
მოდი მოიძიე სხვადასხვა დენსითი ქუალიფაიერების შესახებ (ldpi, mdpi, hdpi ... )png სურათისთვის და თავიდან დააექსპორტე ისინი 
https://developer.android.com/training/multiscreen/screendensities
ასევე ic_happy ვექტორული სურათია და svg უნდა იყოს

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/java/com/space/quiz/MainActivity.kt
>  class MainActivity : AppCompatActivity() {
მეინ კლასებს ექთივითიებს ჯობია თავიდანვე გადავარქვათ სახელი.

ასევე, gitignoreში დაამატე idea-ს ფაილები

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/java/com/space/quiz/presentation/intro/IntroFragment.kt
> +        }
თუ გრედლში ნავიგაციის კომპონენტების დეფენდენსები გაქვს იმპლემენტირებული, ფრაგმენტ მენეჯერს რატომ იყენებ ნავიგაციისთვის?

თუ მომავალ ფულ რექუესტებში აპირებ შეცვლას, TODO დაუწერე

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/java/com/space/quiz/presentation/views/IntroCustomView.kt
> +    }
იგივე რაც დათოს ვუთხარით: პირდაპირ paint შეგიძლია შექმნა და სტილი დინამიურად უცვალო. ასევე რამე ბეიზი გააკეთე ქასთუმ ვიუების სადაც საერთო ლოგიკებს გაიტან

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/java/com/space/quiz/presentation/views/IntroCustomView.kt
> +    }
მოდი შეეცადე რომ პატარა ფუნქციებად დაყო, მაგალითად:
1. drawDarkBlueBackground
2. drawLightBlueBackground და ასე შემდეგ, შინაარობრივადაც უფრო დალაგდება რომელი ნაწილი რისი პასუხისმგებელია

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/java/com/space/quiz/presentation/views/IntroCustomView.kt
> +            addCircle(centerX, centerY2, cornerRadius, Path.Direction.CW)
ორი წრის დამატება რატომ გახდა საჭირო?

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/java/com/space/quiz/presentation/views/IntroCustomView.kt
> +        style = Paint.Style.FILL
antialias თრუ დაამატე

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/java/com/space/quiz/presentation/views/TestsTopCustomView.kt
> +    }
იგივე კომენტარები მექნება აქაც

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/res/layout/congrats_dialog.xml
> +<?xml version="1.0" encoding="utf-8"?>
დიალოგის ვიუ ჯობია რომ ჯენერალ იყოს, რომელსაც არამარტო congrats-ისთვის გამოიყენებ, არამედ ლოგაუთისთვის და შეგიძლია მისცე ორი სთეითი: როცა ერთ ღილაკიანია და როცა ორ ღილაკიანია, ასევე მისცე სურათის გადაცემის საშუალება, რომელიც ხანდახან დაგჭირდება, ხანდახან არა

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/res/layout/exit_dialog.xml
> +        android:text="ნამდვილად გსურს ქვიზის შეწყვეტა?"
გაიტანე რესურსებში

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/res/layout/exit_dialog.xml
> +        android:text="კი"
გაიტანე რესურსებში

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/res/layout/exit_dialog.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
როდესაც ჯენერალ დიალოგის ვიუს შექმნი, არ დაგჭირდება exit და congrats-ის დიალოგის ცალ-ცალკე ლეიაუთების შექმნაც

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/res/layout/exit_dialog.xml
> +        android:text="არა"
გაიტანე რესურსებში

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/res/layout/fragment_details.xml
> +        android:id="@+id/imageView2"
არაშესაფერისი აიდის სახელია

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/res/layout/fragment_details.xml
> +        android:id="@+id/view"
არაშესაფერისი აიდის სახელია

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/res/layout/fragment_home.xml
> +        app:rectangleBackgroundColor="#2CFFFFFF"
გაიტანე რესურსებში. ასევე დიზაინში დააფდეითდა ფერები და გადაამოწმე

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/res/layout/fragment_home.xml
> +    <com.space.quiz.presentation.views.RectangleView
ყოველთვის დააფორმატირე ხოლმე კოდი ctrl alt l -ით

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/res/layout/fragment_intro.xml
> +        android:font="@font/myriad_geo"
შექმენი რამდენიმე ტექსტის სტილი, რომლებშიც იქნება ფონტი, ტექსტის ფერი და ზომა. ზომის მიხედვით გაანაწილე, როგორც small (12), medium (14), large (16) (უმეტესობა რაც გვხვდება) და ნებისმიერი ტექსტვიუს შექმნის დროს style-> მიუთითე შენი შექმნილი სტილები, რომ ყველას არ გაუწერო ფონტი, ზომა, ფერი.

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/res/layout/quiz_subject_items.xml
> +        android:text="გეოგრაფია"
გამოიყენე tools

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/res/values/colors.xml
> +    <color name="wrong">#DB1D2A</color>
wrong ცოტა შეუსაბამო სახელია ფერისთვის. ფიგმაში არ აქვს სახელი ამ ფერს?

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/res/values/strings.xml
> +    <string name="point_number_text">1</string>
მხოლოდ ციფრების გატანა როგორც სტრინგის რესურსი, არაა საჭირო, იგივე ეხება point_text

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/res/values/strings.xml
> +    <string name="points_text">შენ დააგროვე 14 ქულა</string>
14 ქულა უნდა იყოს დინამიური, გამოიყენე სტრინგის ფორმატირება, რომელიც საშუალებას მოგცემს რომ 14-ის მაგივრად დინამიური ცვლადი ჩასვა სტრინგში

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/res/values/strings.xml
> +    <string name="hello_user_text">გამარჯობა,ირაკლი</string>
იუზერის სახელი უნდა იყოს დინამიური, გამოიყენე სტრინგის ფორმატირება, რომელიც საშუალებას მოგცემს რომ ირაკლის მაგივრად დინამიური ცვლადი ჩასვა სტრინგში

2023-05-19 08:32 UTC, AnaRusadze commented on app/src/main/res/values/strings.xml
> +    <string name="unfortunately_text">🧐სამწუხაროდ,ქულები ჯერ არ გაქვს დაგროვილი.</string>
მძიმის შემდეგ ადგილი გამოტოვე ;დ

2023-05-19 09:06 UTC, ninikokra commented on app/src/main/res/values/strings.xml
> +    <string name="unfortunately_text">🧐სამწუხაროდ,ქულები ჯერ არ გაქვს დაგროვილი.</string>
ტექსტი დავაკოპირე ფიგმადან და ეგრე ეწერა :დ

2023-05-19 09:06 UTC, ninikokra commented on app/src/main/res/values/colors.xml
> +    <color name="wrong">#DB1D2A</color>
ფიგმაში ეგრე ქვია :)

2023-05-19 09:08 UTC, ninikokra commented on app/src/main/java/com/space/quiz/presentation/views/IntroCustomView.kt
> +    }
კი, ვაპირებ მაგას, ლექციიდან მახსოვს. უბრალოდ ჯერ ფიზიკურად ვერ მოვასწარი.

2023-05-19 09:11 UTC, ninikokra commented on app/src/main/res/layout/fragment_intro.xml
> +        android:font="@font/myriad_geo"
აუცილებლად, უბრალოდ ბოლომდე მინდოდა რომ გამეწერა ჯერ, რომ მერე ყველა ერთად დამელაგებინა ზომების მიხედვით. შემდეგ ქომითზე იქნება :)

2023-05-23 17:20 UTC, Gio481 requested changes

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/java/com/space/quiz/presentation/base/BaseFragment.kt
> +typealias Inflater<VB> = (inflater: LayoutInflater, container: ViewGroup, attachToRoot: Boolean) -> VB
ამის ადგილი აქ არაა

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/java/com/space/quiz/presentation/views/IntroCustomView.kt
> +        val centerY2 = height * 2 / 3 - heightAdjustment
აჯობებს კომენტარები დაუწერო ეს ფორმულები რას ემსახურებიან

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/java/com/space/quiz/presentation/views/TestsTopCustomView.kt
> +
ამათაც კომენტარები

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/congrats_dialog.xml
> +        android:layout_height="0.8dp"
რესურსებში გინდა 0.8 და რატო დაგჭირდა ბარემ 1 დაგეწერა :დ

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/congrats_dialog.xml
> +        android:layout_height="@dimen/dimen_199dp"
ჰეითი დარწმუნებული ხარ რო 199 გინდა და არაფერს აშავებს ? ;დ

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/exit_dialog.xml
> +        android:layout_height="@dimen/dimen_176dp"
აქაც იგივე ჰეითზე

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/exit_dialog.xml
> +        android:id="@+id/yesTextView"
ფორმატი გინდა

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/exit_dialog.xml
> +        android:id="@+id/noRectangle"
აიდი გაუგებარია

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/fragment_details.xml
> +        android:id="@+id/unfortunatelyTextView"
უფრო ლოგიკური აიდი აჯობებს

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/fragment_details.xml
> +        android:layout_width="@dimen/dimen_195dp"
სიგრძელე ან მაჩ პარენტი ან 0დპ დაუწერე და მარგინები გვერდებიდან ეგრე აჯობებს ვიდრე 195დპ

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/fragment_details.xml
> +        android:text="@string/unfortunately_text"
აქაც სტრინგის რესურსის სახელი უფრო ლოგიკური რო იყოს

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/fragment_details.xml
> +        android:layout_height="0.8dp"
აქაც იგივე ბარემ 1 დაწერე ან რესურსებში გაიტანე

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/fragment_details.xml
> +        android:layout_marginHorizontal="@dimen/dimen_16dp"/>
მარგინი დაუწერე ბარემ

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/fragment_home.xml
> +        android:layout_marginTop="@dimen/dimen_16dp"
აქაც პირდაპირ მარჯინი

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/fragment_home.xml
> +        android:text="GPA -  4.0"
რესურსებში

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/fragment_home.xml
> +        android:id="@+id/view"
შეუსაბამო აიდის სახელია

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/fragment_intro.xml
> +        android:letterSpacing="0"
დეფოლტად არაა 0 ?

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/fragment_intro.xml
> +        android:letterSpacing="0"
აქაც იგივე დეფოლტად რამდენია რო

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/fragment_tests.xml
> +        app:layout_constraintStart_toStartOf="@+id/testsTopRectangle"
კოდის ფორმატირება უნდა

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/fragment_tests.xml
> +        android:src="@drawable/ic_cancel"
პირდაპირ მარჯინ

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/fragment_tests.xml
> +        app:layout_constraintEnd_toEndOf="parent"
ფორმატი გინდა კოდის

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/fragment_tests.xml
> +        android:maxWidth="300dp"
რესურსებში 300დპ

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/fragment_tests.xml
> +        app:layout_constraintHorizontal_bias="0.0"
bias წასაშლელია

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/fragment_tests.xml
> +        android:letterSpacing="0"
ზედმეტი ხო არაა letterSpacing ატრიბუტი

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/quiz_subject_items.xml
> +        android:text="აღწერა"
რესურსებში გინდა

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/layout/quiz_subject_items.xml
> +        android:textColor="@color/hint_text_color"
ტექსტ ქოლორის ფერზე სხვა სახელი მოიფიქრე

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/values/attrs.xml
> +</declare-styleable>
კოდის ფორმატი

2023-05-23 17:20 UTC, Gio481 commented on app/src/main/res/values/dimen.xml
> +    <dimen name="dimen_550dp">550dp</dimen>
ამხელა ზომები რატო დაგჭირდა ?

2023-05-23 17:20 UTC, Gio481 commented
@ninikokra კოდის ფორმატირება გინდა, სტილების დამატება, აიდების გასწორება

2023-05-23 17:40 UTC, ninikokra commented
@Gio481 გიო, ყველაფერი თითქმის რაც დამიწერე შეცვლილი მაქვს და ხვალ ახალ ქომითს გამოვუშვებ და შესწორებული იქნება <3 მადლობა!

2023-05-24 11:52 UTC, ninikokra commented on app/src/main/java/com/space/quiz/presentation/views/IntroCustomView.kt
> +    }
done

2023-05-24 11:52 UTC, ninikokra commented on app/src/main/java/com/space/quiz/presentation/views/IntroCustomView.kt
> +    }
done

2023-05-24 11:58 UTC, ninikokra commented on app/src/main/java/com/space/quiz/presentation/views/IntroCustomView.kt
> +            addCircle(centerX, centerY2, cornerRadius, Path.Direction.CW)
სხვანაირად ვერ გავაკეთე და თან ამ წრეებით ვავსებ შიდა ვიუს და უფრო ემსგავსება იმ დიზაინს რაც ფიგმაში იყო

2023-05-24 11:58 UTC, ninikokra commented on app/src/main/java/com/space/quiz/presentation/views/IntroCustomView.kt
> +        style = Paint.Style.FILL
done

2023-05-24 11:59 UTC, ninikokra commented on app/src/main/java/com/space/quiz/presentation/views/TestsTopCustomView.kt
> +    }
done

2023-05-24 11:59 UTC, ninikokra commented on app/src/main/res/layout/congrats_dialog.xml
> +<?xml version="1.0" encoding="utf-8"?>
გავითვალისწინებ, ჯერჯერობით ეს შემიცვლია

2023-05-24 12:00 UTC, ninikokra commented on app/src/main/res/layout/exit_dialog.xml
> +        android:text="ნამდვილად გსურს ქვიზის შეწყვეტა?"
done

2023-05-24 12:00 UTC, ninikokra commented on app/src/main/res/layout/exit_dialog.xml
> +        android:text="კი"
done

2023-05-24 12:01 UTC, ninikokra commented on app/src/main/res/layout/exit_dialog.xml
> +        android:text="არა"
done

2023-05-24 12:01 UTC, ninikokra commented on app/src/main/res/layout/fragment_details.xml
> +        android:id="@+id/imageView2"
done

2023-05-24 12:01 UTC, ninikokra commented on app/src/main/res/layout/fragment_details.xml
> +        android:id="@+id/view"
done

2023-05-24 12:01 UTC, ninikokra commented on app/src/main/res/layout/fragment_home.xml
> +        app:rectangleBackgroundColor="#2CFFFFFF"
done

2023-05-24 12:01 UTC, ninikokra commented on app/src/main/res/layout/fragment_intro.xml
> +        android:font="@font/myriad_geo"
done

2023-05-24 12:01 UTC, ninikokra commented on app/src/main/res/layout/quiz_subject_items.xml
> +        android:text="გეოგრაფია"
done

2023-05-24 12:02 UTC, ninikokra commented on app/src/main/res/values/strings.xml
> +    <string name="points_text">შენ დააგროვე 14 ქულა</string>
done

2023-05-24 12:02 UTC, ninikokra commented on app/src/main/res/values/strings.xml
> +    <string name="hello_user_text">გამარჯობა,ირაკლი</string>
done

2023-05-24 12:03 UTC, ninikokra commented on app/src/main/java/com/space/quiz/presentation/views/IntroCustomView.kt
> +        val centerY2 = height * 2 / 3 - heightAdjustment
done

2023-05-24 12:03 UTC, ninikokra commented on app/src/main/java/com/space/quiz/presentation/views/TestsTopCustomView.kt
> +
done

2023-05-24 12:04 UTC, ninikokra commented on app/src/main/res/layout/congrats_dialog.xml
> +        android:layout_height="0.8dp"
1 უფრო სქელია და არ ეთანხმება დიზაინს :დ გავიტანე რესურსში :დ

2023-05-24 12:35 UTC, ninikokra commented on app/src/main/res/layout/congrats_dialog.xml
> +        android:layout_height="@dimen/dimen_199dp"
199 რო მინდა დარწმუნებული ვარ :დ მარა რაღაცეებსაც რო აშავებს მაგასაც ვხვდები :დ ეს ლეიაუთი მთლიანად შესაცვლელი გამომდის, ანამ 1 ჯენერალი გააკეთეო, ამიტომ დროებით იყოს ესე :დ

2023-05-24 12:36 UTC, ninikokra commented on app/src/main/res/layout/exit_dialog.xml
> +        android:id="@+id/noRectangle"
ეს საერთოდ წავშალე :დ

2023-05-24 12:36 UTC, ninikokra commented on app/src/main/res/layout/fragment_details.xml
> +        android:id="@+id/unfortunatelyTextView"
done

2023-05-24 12:36 UTC, ninikokra commented on app/src/main/res/layout/fragment_details.xml
> +        android:layout_width="@dimen/dimen_195dp"
done

2023-05-24 12:37 UTC, ninikokra commented on app/src/main/res/layout/fragment_details.xml
> +        android:text="@string/unfortunately_text"
done

2023-05-24 12:37 UTC, ninikokra commented on app/src/main/res/layout/fragment_details.xml
> +        android:layout_height="0.8dp"
done

2023-05-24 12:37 UTC, ninikokra commented on app/src/main/res/layout/fragment_details.xml
> +        android:layout_marginHorizontal="@dimen/dimen_16dp"/>
done

2023-05-24 12:37 UTC, ninikokra commented on app/src/main/res/layout/fragment_home.xml
> +        android:layout_marginTop="@dimen/dimen_16dp"
done

2023-05-24 12:37 UTC, ninikokra commented on app/src/main/res/layout/fragment_home.xml
> +        android:text="GPA -  4.0"
done

2023-05-24 12:37 UTC, ninikokra commented on app/src/main/res/layout/fragment_home.xml
> +        android:id="@+id/view"
done

2023-05-24 12:38 UTC, ninikokra commented on app/src/main/res/layout/fragment_intro.xml
> +        android:letterSpacing="0"
მე მახსოვდა რო დეფოლტად 1 იყო, ვორდში ეგრეა, მაგრამ, თუ არ გავუწერ სფეისინგს, მაინც აკეთებს ოდნავ უფრო დიდს ვიდრე 0ია. ამიტომ მაინც გგავუწერე

2023-05-24 12:38 UTC, ninikokra commented on app/src/main/res/layout/fragment_tests.xml
> +        android:src="@drawable/ic_cancel"
done

2023-05-24 12:39 UTC, ninikokra commented on app/src/main/res/layout/fragment_tests.xml
> +        android:maxWidth="300dp"
done

2023-05-24 12:39 UTC, ninikokra commented on app/src/main/res/layout/fragment_tests.xml
> +        app:layout_constraintHorizontal_bias="0.0"
done

2023-05-24 12:39 UTC, ninikokra commented on app/src/main/res/layout/quiz_subject_items.xml
> +        android:text="აღწერა"
done

2023-05-24 12:39 UTC, ninikokra commented on app/src/main/res/layout/quiz_subject_items.xml
> +        android:textColor="@color/hint_text_color"
სანამ დიზაინერი დაამატებდა დროებით მქონდა, უკვე შევცვალე <3

2023-05-24 12:40 UTC, ninikokra commented on app/src/main/res/values/dimen.xml
> +    <dimen name="dimen_550dp">550dp</dimen>
max width ებისთვის მჭირდებოდა

2023-05-29 09:48 UTC, AnaRusadze requested changes

2023-05-29 09:48 UTC, AnaRusadze commented on app/src/main/java/com/space/quiz/presentation/dialog/CustomDialogView.kt
> +            noTextView.visibility = View.VISIBLE
შეგიძლია გამოიყენო ქონსთრეინთის გრუპი, რომელსაც reference id ექნება ეს სამი ვიუ, ხოლო აქ ვიზიბილითის group-ს შეუცვლი და ავტომატურად იმოქმედებს სამივეზე. ხაზების რაოდენობასაც შეგიმცირებს

2023-05-29 09:48 UTC, AnaRusadze commented on app/src/main/java/com/space/quiz/presentation/dialog/CustomDialogView.kt
> +            noTextView.visibility = View.VISIBLE
შეგიძლია ვიუს პატარა ექსთენშენი დაამატო View.IsVisible (true) ან რამე მსგავსი

2023-05-29 09:48 UTC, AnaRusadze commented on app/src/main/java/com/space/quiz/presentation/dialog/CustomDialogView.kt
> +        return binding.yesTextView
ბათონებს ლისენერები აქ დაადე და აიდის გადაწოდების მაგივრად ქოლბექები გადააწოდე, ლამბდას სახით

2023-05-29 09:48 UTC, AnaRusadze commented on app/src/main/java/com/space/quiz/presentation/home/HomeFragment.kt
> +        val alertDialogBuilder = AlertDialog.Builder(requireContext())
ალერტ დიალოგის შექმნაც ქასთუმ ვიუში უნდა იყოს

2023-05-29 09:48 UTC, AnaRusadze commented on app/src/main/java/com/space/quiz/presentation/views/BaseCustomView.kt
> +open class BaseCustomView(
open რატოა და არა abstract?

2023-05-29 09:48 UTC, AnaRusadze commented on app/src/main/java/com/space/quiz/presentation/views/IntroCustomView.kt
> +            addCircle(centerX, centerY2, cornerRadius, Path.Direction.CW)
ის ბაგი გაასწორე, სხვადასხვა ზომის დივაისის მიხედვით რომ ირღვევა ვიზუალი?

2023-05-29 09:48 UTC, AnaRusadze commented on app/src/main/res/drawable/bckg_textview_shape.xml
> +<?xml version="1.0" encoding="utf-8"?>
bckg პრეფიქსის მაგივრად ჯობია, რომ bkg გამოიყენო

2023-05-29 09:48 UTC, AnaRusadze commented on app/src/main/res/layout/custom_dialog.xml
> +        app:layout_constraintTop_toBottomOf="@+id/congratsTextView" />
ეს სამივე ტექსტვიუ ჯობია ერთში გააერთიანო, ასევე რესურსებიც გააერთიანე

2023-05-29 09:48 UTC, AnaRusadze commented on app/src/main/res/layout/fragment_tests.xml
> +        tools:listitem="@layout/questions_item" />
tools:itemCount="" დაამატე და შეიძლება აღარც დაგჭირდეს სტატიკური ჰეითი. 
მეორე ვარიანტია android:layout_height=0 დაუწერო და გაშლის ქონსთრეინთში თავისუფალ ადგილზე
თუ არ იმუშავებს, მაშინ 
  tools:layout_height="300dp" შეცვალე, რომ მარტო ვიზუალურად აისახოს

2023-05-29 09:48 UTC, AnaRusadze commented on app/src/main/res/layout/quiz_subject_items.xml
> +        android:visibility="visible"
თუ ვიუ დიფოლტად ჩანს მაშინ android:visibility="visible" აღარაა საჭირო

2023-05-29 09:48 UTC, AnaRusadze commented on app/src/main/res/layout/quiz_subject_items.xml
> +        app:layout_constraintHeight_percent="0.88"
0,8 რატომ?

2023-05-29 09:48 UTC, AnaRusadze commented on app/src/main/res/values/colors.xml
> +    <color name="wrong">#DB1D2A</color>
აა კაი ;დდ

2023-05-30 13:08 UTC, ninikokra commented on app/src/main/java/com/space/quiz/presentation/dialog/CustomDialogView.kt
> +            noTextView.visibility = View.VISIBLE
done, done

2023-05-30 13:08 UTC, ninikokra commented on app/src/main/java/com/space/quiz/presentation/dialog/CustomDialogView.kt
> +        return binding.yesTextView
done

2023-05-30 13:08 UTC, ninikokra commented on app/src/main/java/com/space/quiz/presentation/home/HomeFragment.kt
> +        val alertDialogBuilder = AlertDialog.Builder(requireContext())
done

2023-05-30 13:10 UTC, ninikokra commented on app/src/main/res/layout/quiz_subject_items.xml
> +        app:layout_constraintHeight_percent="0.88"
რო გავყავი პროცენტულად სიმაღლე, ეს ყვეალაზე ზუსტად დაემთხვა იმ ზომას რაც მოცემული იყო ფიგმაში.

2023-05-30 13:10 UTC, ninikokra commented on app/src/main/res/layout/quiz_subject_items.xml
> +        android:visibility="visible"
ეს გატესტვისას დამრჩა :დ

2023-05-30 13:10 UTC, ninikokra commented on app/src/main/res/layout/fragment_tests.xml
> +        tools:listitem="@layout/questions_item" />
მადლობა <3

2023-06-01 09:10 UTC, Gio481 approved these changes

2023-06-05 06:43 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz/QuizActivity.kt
> +        val navHostFragment =
ამის გარეშეც მუშაობს ნავიგაცია

2023-06-05 07:07 UTC, DavitTsiskarashvili commented on app/src/main/res/drawable/bkg_textview_shape.xml
ჰარდად არც აქ უნდა იყოს გაწერილი ზომები

2023-06-05 07:17 UTC, DavitTsiskarashvili commented on app/src/main/res/values/strings.xml
> +    <string name="no_result_point_text">🧐სამწუხაროდ,ქულები ჯერ არ გაქვს დაგროვილი.</string>
მძიმის მერე ადგილი გამოტოვე

2023-06-05 07:18 UTC, DavitTsiskarashvili commented on app/src/main/res/values/strings.xml
> +    <string name="hello_user_text">გამარჯობა,%1$s</string>
აქაც მძიმის მერე ადგილის გამოტოვება

2023-06-05 07:20 UTC, DavitTsiskarashvili commented on app/src/main/res/values/text_style.xml
> +    <style name="xxlMyriadGeo_white_bold">
xxl რა სახელია :D

2023-06-05 07:20 UTC, DavitTsiskarashvili commented on app/src/main/res/values/text_style.xml
> +    <style name="xxlMyriadGeo_darkGrey_normal">
აქაც :D

2023-06-05 07:22 UTC, DavitTsiskarashvili commented on app/src/main/res/values/text_style.xml
> +    <style name="smallMyriadGeo_lGrey_normal">
lGrey ჩაი ვიცი მე :D დაარქვი სრულად light_grey

2023-06-05 09:54 UTC, iTarley commented on app/src/main/java/com/space/quiz/presentation/home/HomeFragment.kt
> +    }
ფუნქციის სახელი ისე შეცვალე რომ ზმნა გამოვიდეს

2023-06-05 09:54 UTC, iTarley commented on app/src/main/java/com/space/quiz/presentation/views/CustomTitleView.kt
> +    }
with(binding) გამოიყენე ხოლმე როცა 2-ზე მეტი მაინც გაქვს

2023-06-05 09:54 UTC, iTarley commented on app/src/main/res/layout/fragment_intro.xml
> +        app:layout_constraintHeight_percent="0.6"
0.5 უნდა უყოს

2023-06-05 10:09 UTC, ninikokra commented on app/src/main/java/com/space/quiz/presentation/home/HomeFragment.kt
> +    }
done

2023-06-05 10:09 UTC, ninikokra commented on app/src/main/res/layout/fragment_intro.xml
> +        app:layout_constraintHeight_percent="0.6"
done

2023-06-05 10:11 UTC, ninikokra commented on app/src/main/java/com/space/quiz/presentation/views/CustomTitleView.kt
> +    }
done

2023-06-06 08:15 UTC, iTarley approved these changes

2023-06-06 14:54 UTC, AnaRusadze approved these changes

2023-06-06 14:55 UTC, DavitTsiskarashvili approved these changes

2023-06-06 15:40 UTC, merged