[CMOB-1526]feature/user registration
ninikokra/Quiz pull request #2
Opened 2023-06-06 21:55 UTC by ninikokra

https://spaceneobank.atlassian.net/browse/CMOB-1526

2023-06-07 06:50 UTC, Gio481 requested changes

2023-06-07 06:50 UTC, Gio481 commented on app/build.gradle
> +    implementation "org.jetbrains.kotlin:kotlin-reflect:1.8.10"
ამის იმპლემენტაცია რას აკეთებს რატოა საჭიროო ?

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/data/local/mapper/UserDomainToEntityMapper.kt
> +    override fun invoke(model: DomainUserModel): UserEntity =
UserDomain

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/data/local/mapper/UserDomainToEntityMapper.kt
> +        )
with(model)

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/data/repository/UserRepositoryImpl.kt
> +    private val domainToEntity: UserDomainToEntityMapper
UserEntityMapper
UserDomainMapper

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/data/repository/UserRepositoryImpl.kt
> +    private val domainToEntity: UserDomainToEntityMapper
ცვლადის სახელებიც არაა კარგი, შეცვალე

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/di/UseCaseModule.kt
> +    single<SaveUserUseCase> { SaveUserUseCaseImpl(get()) }
წინა რევიუდან გამომდინარე, ყველა იუს ქეის თავისი ინტერფეისები ხო არ უნდა გაუკეთო, ერთი ბეიზი გააკეთე ყველასთვის

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/di/UserRepositoryModule.kt
> +    }
ფორმატი უნდა

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/di/ViewModelModule.kt
> +        IntroViewModel(get(), UserPresentationToDomainMapper())
UserUiMapper
მაპერს თავისი di გაუკეთე და აქ გეთით ამოიღე

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/domain/model/DomainUserModel.kt
> +data class DomainUserModel(
UserDomain

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/domain/usecase/save_user/SaveUserUseCase.kt
> +    suspend fun saveUser(user: DomainUserModel):Boolean
სეივ იუზერი თრუს რატო აბრუნებს, ამ სახელით ფუნქციის მოვალეობაა პროსტა ჩასეტოს ბაზაში იუზერი და არა ბულიანი დააბრუნოს

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/domain/usecase/save_user/SaveUserUseCaseImpl.kt
> +    }
არაა ფუნქციის მოქმედება და გამოყენება სწორი, სხვა გზა ნახე ვალიდაციისთვის და იუზერის შენახვისთვის

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/presentation/base/BaseFragment.kt
>  typealias Inflater<VB> = (inflater: LayoutInflater, container: ViewGroup, attachToRoot: Boolean) -> VB
ტაიპალიასის ადგილი არაა ბეიზ ფრაგმენტის ფაილში, წინა პროექტშიც იყოს მსგავსი კომენტარი

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/presentation/fragment_intro/ui/IntroFragment.kt
> +         }*/
ეს რატოა კომეტარში

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/presentation/fragment_intro/ui/IntroFragment.kt
> +                ).show()
ტოასტის ექსთენშენი გინდა

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/presentation/fragment_intro/ui/IntroFragment.kt
> +            observeResource(viewModel)
ობსერვერი კლიკის შიგნით რო გიწერია არაა სწორი

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/presentation/fragment_intro/ui/IntroFragment.kt
> +                ).show()
ეს რამხელა ლოგიკა გიწერია ფრაგმენტში, ვმს რატო არ ტვირთავ

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/presentation/fragment_intro/ui/IntroFragment.kt
> +                    // Toast.makeText(requireContext(), "გეეეყყყოოოფფფააა", Toast.LENGTH_SHORT).show()
ეს ხაზი უნდა იყოს პრში ? 😃

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/presentation/fragment_intro/ui/IntroFragment.kt
> +                }
სიმართლე გითხრა მე არ მომწონს ასეთი რამე ფრაგმენტში და ნუ თუ სხვა სოლუშენს ვერ ნახულობ იყოს მაშინ :დ

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/presentation/fragment_intro/ui/IntroFragment.kt
> +        customDialogView.showDialog()
CustomDialogView(requireContext().apply {}

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/utils/CoroutineExtension.kt
> +fun <T> LifecycleOwner.collectInLifecycleScope(
ფრაგმენტზე რო გააკეთო უფრო არ აჯობებს ?

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/presentation/fragment_questions/ui/TestsFragment.kt
> +class TestsFragment : BaseFragment<FragmentTestsBinding, QuestionsViewModel>() {
ტესტ ფრაგმენტით რას ტესტავ

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/presentation/fragment_intro/vm/IntroViewModel.kt
> +        }
ეს ფუნქცია წასაშლელია ჩემი აზრით და სეივ იუზერს რო დააოპტიმიზირებ იუს ქეისში მერე შესაბამისი ფუნქცია გამოდგი აქაც

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/presentation/model/PresentationUserModel.kt
> +    val id: Int? = null,
კლასს შეუცვალე სახელი და აიდი რატო გჭირდება ისე ?

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/presentation/model/mapper/UserPresentationToDomainMapper.kt
> +class UserPresentationToDomainMapper :ModelMapper<PresentationUserModel,DomainUserModel> {
ui mapper

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/utils/Resource.kt
> +}
ფორმატი უნდა და ყველა კლასს  უნდა ვგონებ :დ

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/utils/ValidationExtension.kt
> +fun isUserNameCorrect(username: String): Boolean {
ფუნქციას სახელი გადაარქვი და წინა რევიუდან გამომდინარე სწორია ასე ფაილში რო გიგდია შენი აზრით  და რატო ? :დ

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/java/com/space/quiz/utils/ValidationExtension.kt
> +    return username.matches(regex)
პატარა ჯავა დოკიც რო დაუწერე რას მაჩავ კაი იქნება

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/res/layout/fragment_intro.xml
>          android:id="@+id/blueRectCustomView"
ლურჯი თუა იქსემელიდან გადააწოდე ლურჯი ფერი რო ლურჯი იყოს

2023-06-07 06:50 UTC, Gio481 commented on app/src/main/res/values/strings.xml
>      <string name="choose_subject_text">აირჩიე საგანი</string>
ნახე ზოგზე გიწერია სახელი_ტექსტი და ზოგზე პირდაპირ სახელი და ერთნაირად რო გქონდეს ყველაფერი აჯობებს

2023-06-07 06:51 UTC, Gio481 commented
ფექიჯებში ფრაგმენტის დასახელება აღარ უნდა

2023-06-07 07:10 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz/di/UserDatabaseModule.kt
ყველა მოდული di ფექიჯში გაქვს, თუმცა უფრო სწორია მოდელები ინდივიდუალურ ლეიერებში იყოს. მაგ. ვიუმოდელის მოდული Presentation package-ში, databaseModule data-ში და ა.შ.

2023-06-07 07:19 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz/presentation/fragment_intro/ui/IntroFragment.kt
> +                }
ნავიგაცია ვიუმოდელში უნდა გაიტანო

2023-06-07 08:04 UTC, ninikokra commented on app/src/main/java/com/space/quiz/presentation/fragment_intro/ui/IntroFragment.kt
> +         }*/
ეს დიალოგი ამ ფრაგმენტზე არ არის წესით. როდესაც ქვიზი მორჩება მაშინ უნდა გამოვიდეს. სანამ მაქამდე მივალ, გასატესტად, რამდენად სწორად მუშაობს და იხატება ამ ბათონზე მაქვს მიბმული, საჩვენებლად რომ მქონდეს.

2023-06-07 08:10 UTC, ninikokra commented on app/src/main/java/com/space/quiz/presentation/fragment_intro/ui/IntroFragment.kt
> +                ).show()
done

2023-06-07 09:39 UTC, ninikokra commented on app/src/main/java/com/space/quiz/di/UseCaseModule.kt
> +    single<SaveUserUseCase> { SaveUserUseCaseImpl(get()) }
done

2023-06-07 10:13 UTC, ninikokra commented on app/src/main/java/com/space/quiz/di/ViewModelModule.kt
> +        IntroViewModel(get(), UserPresentationToDomainMapper())
done

2023-06-16 10:47 UTC, Gio481 approved these changes

2023-06-16 12:17 UTC, gioqemoklidze requested changes

2023-06-16 12:17 UTC, gioqemoklidze commented on app/src/main/java/com/space/quiz/presentation/base/BaseFragment.kt
> +  /*  fun navigateTo(destinationId: Int) {
why is this commented ?

2023-06-16 12:17 UTC, gioqemoklidze commented on app/src/main/java/com/space/quiz/presentation/ui_intro/vm/IntroViewModel.kt
> +import com.space.quiz.presentation.base.BaseViewModel
where is base viewModel class ?

2023-06-16 12:17 UTC, gioqemoklidze commented on app/src/main/java/com/space/quiz/presentation/ui_intro/ui/IntroFragment.kt
> +        authenticateUser(viewModel)
why is this commented ?

2023-06-16 12:17 UTC, gioqemoklidze commented on app/src/main/java/com/space/quiz/presentation/ui_intro/ui/IntroFragment.kt
> +}
why is this commented ?

2023-06-16 12:17 UTC, gioqemoklidze commented on app/src/main/java/com/space/quiz/presentation/ui_intro/ui/IntroFragment.kt
> +            val currentUser = binding.inputNameEditText.text.toString()
use with(binding) and move val currentUser in first block of if you will avoid creating extra variable if its not needed

2023-06-16 12:17 UTC, gioqemoklidze commented on app/src/main/java/com/space/quiz/presentation/ui_intro/vm/IntroViewModel.kt
> +    private val userUIToDomain: UserUIDomainMapper
userUIToDomainMapper

2023-06-16 12:17 UTC, gioqemoklidze commented on app/src/main/java/com/space/quiz/presentation/ui_home/ui/HomeFragment.kt
> +         toQuestionsFragment()*/
why is this commented

2023-06-16 12:17 UTC, gioqemoklidze commented on app/src/main/java/com/space/quiz/presentation/ui_home/ui/HomeFragment.kt
> +}
why navigations is written here and comented ?

2023-06-16 12:17 UTC, gioqemoklidze commented on app/src/main/java/com/space/quiz/presentation/ui_home/ui/HomeFragment.kt
> +        customDialogView.showDialog()
use CustomDialogView(requireContext()).apply and why is setNegativeButtonClickListener empty ?

2023-06-16 12:17 UTC, gioqemoklidze commented on app/src/main/java/com/space/quiz/presentation/ui_home/ui/HomeFragment.kt
> +import kotlin.reflect.KClass
unused imports

2023-06-16 12:17 UTC, gioqemoklidze commented on app/src/main/java/com/space/quiz/presentation/ui_details/ui/DetailsFragment.kt
>          titleView.collectedPointsToolBar()
try HeaderView(requireContext()).apply and try to move navigation in viewModel

2023-06-16 12:17 UTC, gioqemoklidze commented on app/src/main/java/com/space/quiz/presentation/ui_questions/ui/QuestionsFragment.kt
> +import com.space.quiz.R
unused import

2023-06-16 12:17 UTC, gioqemoklidze commented on app/src/main/java/com/space/quiz/presentation/ui_questions/ui/QuestionsFragment.kt
> +        binding.root.addView(titleView)
try HeaderView.apply here to and try to move navigation in vm

2023-06-16 12:17 UTC, gioqemoklidze commented on app/src/main/java/com/space/quiz/presentation/views/HeaderView.kt
empty space also ic_yellow_star cant be found at line 22

2023-06-20 12:02 UTC, gioqemoklidze approved these changes

2023-06-20 14:02 UTC, DavitTsiskarashvili approved these changes

2023-06-21 09:41 UTC, AnaRusadze approved these changes

2023-06-21 09:41 UTC, merged