[CMOB-1777]Refactor/home_fragment
ninikokra/Quiz pull request #4
Opened 2023-06-23 11:26 UTC by ninikokra

https://spaceneobank.atlassian.net/browse/CMOB-1777

2023-06-23 13:33 UTC, Gio481 requested changes

2023-06-23 13:33 UTC, Gio481 commented on app/src/main/java/com/space/quiz/data/repository/SubjectRepositoryImpl.kt
ფორმატი უნდა

2023-06-23 13:33 UTC, Gio481 commented on app/src/main/java/com/space/quiz/data/repository/SubjectRepositoryImpl.kt
> +
ცუდი გადაწყვეტილებაა ლისტი, რატო დაგჭირდა ?

2023-06-23 13:33 UTC, Gio481 commented on app/src/main/java/com/space/quiz/data/repository/SubjectRepositoryImpl.kt
>                      }
ჯენერიქ ფუნქციად გაიტანე რო ყოველ ჯერზე არ დაგჭირდეს ტრაის დაწერა და ქეჩი არ უნდა ამას, თუ აქვს

2023-06-23 13:33 UTC, Gio481 commented on app/src/main/java/com/space/quiz/data/repository/SubjectRepositoryImpl.kt
> +        } ?: emptyList()
ეს ფუნქცია რატო რეპოში ?

2023-06-23 13:33 UTC, Gio481 commented on app/src/main/java/com/space/quiz/di/MapperModule.kt
> +    single { QuestionsDomainUIMapper() }
DtoToDomainMapper da DtoDomainMapper მსგავსი სტილიდ დაარქვი ყველას სახელი

2023-06-23 13:33 UTC, Gio481 commented on app/src/main/java/com/space/quiz/di/UseCaseModule.kt
> +    single { SaveDatastoreUseCase(get()) }
SaveDatastore ანუ დათასტორს ინახავ :დ გადაარქცი სახელი

2023-06-23 13:33 UTC, Gio481 commented on app/src/main/java/com/space/quiz/di/UseCaseModule.kt
> +    single { GetSubjectUseCaseImpl(get()) }
იმპლ აღარ უნდა

2023-06-23 13:33 UTC, Gio481 commented on app/src/main/java/com/space/quiz/domain/usecase/datastore/read/ReadDatastoreUseCase.kt
> -}*/
რაღაც არ გაქ ლოგიკურად გამართული იუსქეისები თუ სახელები დატასტორთან მიმართებაში, ეს ვერ გავიგე რას აკეთებს

2023-06-23 13:33 UTC, Gio481 commented on app/src/main/java/com/space/quiz/domain/usecase/datastore/save/SaveDatastoreUseCase.kt
>              userRepository.save(username)
სეივ არაა კარგი ფუნქციის სახელი

2023-06-23 13:33 UTC, Gio481 commented on app/src/main/java/com/space/quiz/presentation/base/BaseFragment.kt
>  typealias Inflater<VB> = (inflater: LayoutInflater, container: ViewGroup, attachToRoot: Boolean) -> VB
ჯერ თუ ვერ აკეთებ ექსთენშენს ეს გაიატანე და იქ დააწერე თავზე

2023-06-23 13:33 UTC, Gio481 commented on app/src/main/java/com/space/quiz/presentation/ui_home/ui/HomeFragment.kt
>              layoutManager = LinearLayoutManager(requireContext())
ლეიაუთ მენეჯერი შეგიძლია პირდაპირ იქსემელიდან გაუწერო

2023-06-23 13:33 UTC, Gio481 commented on app/src/main/java/com/space/quiz/presentation/ui_home/ui/HomeFragment.kt
> +        }
ექსთენშენი გააკეთე რო პროსტა ქოლექთს ფუნქცია გეწეროს

2023-06-23 13:33 UTC, Gio481 commented on app/src/main/java/com/space/quiz/presentation/ui_home/ui/HomeFragment.kt
>                  }
ამასაც გაუკეთე ექსთენშენი

2023-06-23 13:33 UTC, Gio481 commented on app/src/main/java/com/space/quiz/presentation/ui_home/vm/HomeViewModel.kt
> +    val isLoading: StateFlow<Boolean> = _isLoading
შენც იგივეს დაგიწერ :დ ორი ცვლადის მაგივრად ერთი გააკეთე რომელსაც მნიშვნელობას შეუცვლი ვმში და ფრაგმენტში დააქოლექთებ

2023-06-23 13:33 UTC, Gio481 commented on app/src/main/java/com/space/quiz/presentation/ui_home/vm/HomeViewModel.kt
> +                            _isLoading.value = responseHandler.isLoading
ეს რა არის, რამხელა ფუნქციაა ქლინ აფი უნდა

2023-06-27 09:29 UTC, ninikokra commented on app/src/main/java/com/space/quiz/data/repository/SubjectRepositoryImpl.kt
> +
გიო, რივიუზე ავხსენი :(  ჩემთვის ეს იყო ამ ეტაპზე მოსახერხებელი. <3 ლისტი იიმისთვის დამჭრდა რომ საბჯექთები შემენახა ლისტში, რომ შემდეგ ადვილად მემართაა ქუესჩენები, საბჯექთები და ანსვერები

2023-06-27 09:30 UTC, ninikokra commented on app/src/main/java/com/space/quiz/data/repository/SubjectRepositoryImpl.kt
>                      }
შენი ლექციიდან მოყოლებული, სქრინი მქონდა შენახული :)))) ძალიან გამომადგა მადლობა <3

2023-06-27 09:31 UTC, ninikokra commented on app/src/main/java/com/space/quiz/di/MapperModule.kt
> +    single { QuestionsDomainUIMapper() }
done

2023-06-27 09:32 UTC, ninikokra commented on app/src/main/java/com/space/quiz/di/UseCaseModule.kt
> +    single { GetSubjectUseCaseImpl(get()) }
done

2023-06-27 09:34 UTC, ninikokra commented on app/src/main/java/com/space/quiz/di/UseCaseModule.kt
> +    single { SaveDatastoreUseCase(get()) }
done

2023-06-27 09:36 UTC, ninikokra commented on app/src/main/java/com/space/quiz/domain/usecase/datastore/read/ReadDatastoreUseCase.kt
> -}*/
რინეიმი გავუკეთე. ეს გეთს აკეთებს. შევცვალე <3

2023-06-27 09:37 UTC, ninikokra commented on app/src/main/java/com/space/quiz/domain/usecase/datastore/save/SaveDatastoreUseCase.kt
>              userRepository.save(username)
done

2023-06-27 09:46 UTC, ninikokra commented on app/src/main/java/com/space/quiz/presentation/ui_home/ui/HomeFragment.kt
>                  }
ეს გაკეთებული მქონდა და გავასწორე.

2023-06-27 09:46 UTC, ninikokra commented on app/src/main/java/com/space/quiz/presentation/ui_home/ui/HomeFragment.kt
> +        }
ეს ვერ გავაკეთე :(

2023-06-27 11:24 UTC, ninikokra commented on app/src/main/java/com/space/quiz/presentation/ui_home/vm/HomeViewModel.kt
> +    val isLoading: StateFlow<Boolean> = _isLoading
ვერ გავაკეთე ეს. იყოს დროებით სანამ გამოსავალს ვიპოვი

2023-06-27 11:28 UTC, ninikokra commented on app/src/main/java/com/space/quiz/presentation/ui_home/vm/HomeViewModel.kt
> +                            _isLoading.value = responseHandler.isLoading
ვეცდები :დ

2023-07-04 06:52 UTC, Gio481 approved these changes

2023-07-04 06:59 UTC, merged